/**
 * Registry of every stable, machine-readable error identifier the package can emit.
 */
export const ERROR_CODES = {
  REPO_PATH_MISSING: "REPO_PATH_MISSING",
  REPO_PATH_NOT_FOUND: "REPO_PATH_NOT_FOUND",
  REPO_PATH_NOT_A_DIRECTORY: "REPO_PATH_NOT_A_DIRECTORY",
  REPO_PATH_NOT_A_GIT_REPOSITORY: "REPO_PATH_NOT_A_GIT_REPOSITORY",
  ARTIFACT_NOT_FOUND: "ARTIFACT_NOT_FOUND",
  ARTIFACT_FRONTMATTER_MISSING: "ARTIFACT_FRONTMATTER_MISSING",
  ARTIFACT_FRONTMATTER_UNPARSABLE: "ARTIFACT_FRONTMATTER_UNPARSABLE",
  ARTIFACT_FIELD_INVALID: "ARTIFACT_FIELD_INVALID",
  ARTIFACT_FIELD_UNKNOWN: "ARTIFACT_FIELD_UNKNOWN",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
